export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_THESIS_BEGIN = "CREATE_THESIS_BEGIN";
export const CREATE_THESIS_SUCCESS = "CREATE_THESIS_SUCCESS";
export const CREATE_THESIS_ERROR = "CREATE_THESIS_ERROR";

export const GET_THESES_BEGIN = "GET_THESES_BEGIN";
export const GET_THESES_SUCCESS = "GET_THESES_SUCCESS";

export const SET_EDIT_THESIS = "SET_EDIT_THESIS";

export const DELETE_THESIS_BEGIN = "DELETE_THESIS_BEGIN";

export const EDIT_THESIS_BEGIN = "EDIT_THESIS_BEGIN";
export const EDIT_THESIS_SUCCESS = "EDIT_THESIS_SUCCESS";
export const EDIT_THESIS_ERROR = "EDIT_THESIS_ERROR";

export const RESERVE_THESIS_SUCCESS = "RESERVE_THESIS_SUCCESS";
export const APPROVE_THESIS = "APPROVE_THESIS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_USERS = "GET_USERS";

export const GET_STUDENT_THESIS = "GET_STUDENT_THESIS";
export const UPLOAD_THESIS_ATTACHMENT = "UPLOAD_THESIS_ATTACHMENT";
export const GET_THESIS_ATTACHMENTS = "GET_THESIS_ATTACHMENTS";
export const REVIEW_THESIS = "REVIEW_THESIS";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const GET_THESIS_COMMENTS = "GET_THESIS_COMMENTS";
